version: '3'

services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    volumes:
      - ./data:/app/data
    depends_on:
      - database
    env_file:
      - .env

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
