aws_region      = "us-east-1"
instance_type   = "t2.micro"
key_name        = "pa-kd"
vpc_id          = "your-vpc-id"
subnet_id       = "your-subnet-id"
private_key_path = "/path/to/your/private-key"
sg_id           = "sg-0d04b55772575d911"
